client/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings
from . import views

# python manage.py createsuperuser
app_name = 'client'

urlpatterns = [
	#Leave as empty string for base url
	path('', views.store, name="store"),
	path('<int:id>', views.store_eater, name="eater"),
	path('category/<int:id>', views.store_category, name="category"),
	path('view/<int:id>', views.detail_iteam, name="detail"),

	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),

	path('booking/', views.booking, name="booking"),
	path('booking/<int:pk>/delete', views.BookingDelete.as_view(), name="booking-delete"),
    path('cart/<int:pk>/delete', views.CartDelete.as_view(), name='cart-delete'),
	# ajax
	path('norm', views.normal_order, name="nornal"),
	path('camment', views.normal_comment, name="comment"),

    path('profile', views.profile_view, name='profile'),
    path('search', views.search, name='search'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



"""	
	path('checkout/', views.checkout, name="checkout"),

	path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),"""

pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#from pizza import views
from . import views


#app_name = 'pizza'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user_management.urls')),
    path('iteam/', include('client.urls')),
    path('', views.homepage, name='homepage'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

client/forms.py
import email
from datetime import datetime

# import self as self
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from .models import ShippingAddress, OrderItem, Booking, AddedThePizza, Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from django.contrib.auth import authenticate, login



class ProductDetailForm(forms.ModelForm):
    """
        form per articolo con i diversi field e insieme a crispy
    """
    def __init__(self, *args, **kwargs):
        """if AddedThePizza.DoesNotExist or False  :
            alll = AddedThePizza.objects.all()
        else:
            alll = []
            """
        super(ProductDetailForm, self).__init__(*args, **kwargs)
        alll = AddedThePizza.objects.all()
        id_list = [foo.id for foo in alll]
        name_list = [foo.name for foo in alll]
        ADDPIZZA_CHOICES = list(zip(id_list, name_list))
        self.fields['side_dish']  = forms.CharField(initial=0,widget=forms.Select(choices=ADDPIZZA_CHOICES))

    quantity = forms.IntegerField(min_value=1, max_value=10, initial=1 , label="Quntita:")
    class Meta:
        model = OrderItem
        fields = ('size', 'quantity')



class BookingForm(forms.ModelForm):
    """
        form per articolo con i diversi field e insieme a crispy
    """
    chair = forms.IntegerField(initial=1,min_value=1,max_value=10)
    date_start = forms.DateTimeField( input_formats=['%d/%m/%Y %H:%M'], widget=forms.DateTimeInput(attrs={ 'class': 'form-control datetimepicker-input','data-target': '#datetimepicker1'}))
    date_end = forms.DateTimeField( input_formats=['%d/%m/%Y %H:%M'], widget=forms.DateTimeInput(attrs={ 'class': 'form-control datetimepicker-input','data-target': '#datetimepicker1'}))
    class Meta:
        model = Booking
        fields = ('name','description', 'chair','date_start', 'date_end')


class CommentForm(forms.ModelForm):
    """
        form per articolo con i diversi field e insieme a crispy
    """
    rate = forms.IntegerField(initial=1,min_value=1,max_value=5)
    class Meta:
        model = Comment
        fields = ('comment','rate')


class SearchForm(forms.Form):
    """
        form per articolo con i diversi field e insieme a crispy
    """
    search = forms.CharField(required=False)


class ShipForm(forms.ModelForm):
    #n_cart = forms.IntegerField(min_value=0, max_value=3, initial=0 , label="Non analizzare i termini con un numero di lettere inferiore a:", widget=forms.Select(choices=CHARACTERS_CHOICES))
    #data = forms.DateField(label="Data (AAAA-MM-GG)")
    class Meta:
        model = ShippingAddress
        fields = ('address', 'city', 'state', 'zipcode', 'card_pay')




class ProductOrderForm(forms.Form):
    choices = [(0, 'not'),(1, 'ascending name'), (2, 'descending name'), (3, 'ascending price'),  (4, 'descending price')]
    #tank = forms.ChoiceField(choices=choices,  widget=forms.Select(attrs={'onchange': 'actionform.submit();'}))
    tank = forms.ChoiceField(choices=choices,  widget=forms.Select(attrs={"onChange":'submit()'}))
    #tank  = forms.CharField(initial=0, required=False,widget=forms.Select(choices=CHARACTERS_CHOICES))

client/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import datetime
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from .models import *
from .forms import *
#from .utils import cookieCart, cartData, guestOrder

from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages


def emaail_local(subject, message, email_from, recipient_list):
    print("##########################################################################")
    print("\n\n\nSubject : "+subject)
    print("Email_from : "+ email_from)
    print("Message : "+ message)
    print("Recipient_list : "+ recipient_list+"\n\n\n")
    print("##########################################################################")


def store(request):
    form2 = None
    products = None
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data.get('search'))
            products = Product.objects.filter(Q(name__contains=form.cleaned_data.get('search')) |
                                              Q(description__contains=form.cleaned_data.get('search')) |
                                              Q(type_eater__contains=form.cleaned_data.get('search')) ).order_by('name')

            context = {'products': products}
            return render(request, 'product/product.html', context)

    elif request.method == 'GET' and request.GET.get('tank', False) :
        print(request.GET.get('tank'))
        if request.GET.get('tank') == '1':
            products = Product.objects.all().order_by('name')
        elif request.GET.get('tank') == '2' :
            products = Product.objects.all().order_by('-name')
        elif request.GET.get('tank') == '3' :
            products = Product.objects.all().order_by('price')
        else:
            products = Product.objects.all().order_by('-price')


        form = SearchForm()
        form2 = ProductOrderForm()
    else:
        products = Product.objects.all().order_by('price')
        form = SearchForm()
        form2 = ProductOrderForm()

    context = {'form':form, 'form2':form2,'products': products }
    return render(request, 'product/product.html', context)


def store_eater(request,id):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data.get('search'))
            products = Product.objects.filter(Q(name__contains=form.cleaned_data.get('search')) |
                                              Q(description__contains=form.cleaned_data.get('search')) |
                                              Q(type_eater__contains=form.cleaned_data.get('search')) ).order_by('name')
            context = {'products': products}
            return render(request, 'product/product.html', context)
    else:
        if id == 1:
            products = Product.objects.filter(type_eater="vegan")
        elif id == 2:
            products = Product.objects.filter(type_eater="vegetarian")
        else:
            products = Product.objects.filter(type_eater="carnivore")
        form = SearchForm()

    context = {'form':form, 'products': products }
    return render(request, 'product/product.html', context)


def store_category(request,id):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data.get('search'))
            products = Product.objects.filter(Q(name__contains=form.cleaned_data.get('search')) |
                                              Q(description__contains=form.cleaned_data.get('search')) |
                                              Q(type_eater__contains=form.cleaned_data.get('search')) ).order_by('name')
            context = {'products': products}
            return render(request, 'product/product.html', context)
    else:
        if id == 1:
            products = Product.objects.filter(type_product="other")
        elif id == 2:
            products = Product.objects.filter(type_product="drink")
        else:
            products = Product.objects.filter(type_product="sweet")
        form = SearchForm()

    context = {'form':form, 'products': products }
    return render(request, 'product/product.html', context)


# http://127.0.0.1:8000/accounts/login?next=/iteam/view/2
def normal_order(request):
    #product = Product.objects.get(id=id)
    #print(request.POST.get('username'))
    data = { 'is_taken': False }
    if request.method == 'POST' and request.user.is_authenticated:
        data = { 'is_taken': True }
        customer = request.user
        product = Product.objects.get(id=request.POST.get('username'))
        order,created = Order.objects.get_or_create(customer=customer, complete=False)
        adpizza = AddedThePizza.objects.get(name="niente")
        orde = OrderItem.objects.create(product=product,order=order,size="normale",quantity=1,date_added=datetime.today().strftime('%Y-%m-%d'),addpizza=adpizza)
        orde.save()
        return JsonResponse(data)
    return JsonResponse(data)

#ajax
def normal_comment(request):
    data = { 'is_taken': False }
    if request.method == 'POST' and request.user.is_authenticated:
        data = { 'is_taken': True }

        product = Product.objects.get(id=request.POST.get('product'))
        com = Comment.objects.create(comment=request.POST.get('comment'), rate=request.POST.get('rate'),product=product, customer=request.user)
        com.save()
        return JsonResponse(data)
    return JsonResponse(data)


# AJAX non si puo mandare varile url template con int id in ajax likeeeeee {% url 'client:detail' product.id %}
# AJAX pero si possono fare degli escamotage(----with trick---) mettere url in un attributo e dopo con le funzioni javascipt o jquery
# AJAX O COME HO FATTO IO SOPRA
@login_required(login_url='/accounts/login')
def detail_iteam(request, id):
    rate = 0
    media_star = 0
    comment = []
    count = 0
    product = Product.objects.get(id=id)
    products2 = []
    ycomment=[]
    #print(product.type_eater)
    if request.method == 'POST':
        customer = request.user
        form = ProductDetailForm(request.POST)

        if form.is_valid():
            print(form.cleaned_data.get('side_dish'))
            order,created = Order.objects.get_or_create(customer=customer, complete=False)
            orderItem = form.save(commit=False)
            orderItem.product = product
            orderItem.order = order
            orderItem.addpizza = AddedThePizza.objects.get(id=form.cleaned_data.get('side_dish')) # devo aggiungere 0 default 0
            orderItem.date_added = datetime.today().strftime('%Y-%m-%d')
            orderItem.save()
            messages.success(request, 'Aggiunto al carrello!')
        else:
            messages.error(request, 'Salvataggio non ha avuto successo!')

        return redirect('client:store')
    else:
        form = ProductDetailForm()
        comment = Comment.objects.filter(product=product)
        ycomment = Comment.objects.filter(Q(product__type_eater=product.type_eater), ~Q(product=product))
        ycomment2 = ycomment.values_list('product', flat=True)
        try:
            products2 = Product.objects.filter(Q(type_eater=product.type_eater), ~Q(id=id), ~Q(id__in=ycomment2))
            #products2 = Product.objects.filter(Q(type_eater=product.type_eater), ~Q(id=id))
        except Order.DoesNotExist:
            products2 = []

        print(ycomment)
        print(products2)
        for x in comment:
            rate = x.rate + rate
        count = Comment.objects.filter(product=product).count()
        try:
            media_star =  (rate / count)
        except ZeroDivisionError:
            media_star = 0
        #form2 = CommentForm()

    context = {'product': product, 'products2': products2, 'ycomment': ycomment,'form':form, 'media_star':media_star, 'comment':comment, 'count':count}
    return render(request, 'product/product_view.html', context)


# ancora da sistemare
@login_required(login_url='/accounts/login')
def checkout(request):
    items = None
    order = None
    customer = request.user
    if request.method == 'POST':
        form = ShipForm(request.POST)
        if form.is_valid():
            form.save()
            complete_rder = Order.objects.get(customer=customer, complete=False)
            complete_rder.complete=True
            complete_rder.date_ordered=timezone.now()
            complete_rder.save()
            # eamil
            subject = 'Thank you for checkout to our site'
            message = "see you next time. date order : " + str(complete_rder.date_ordered)
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [complete_rder.customer.email]
            #recipient_list = ['jaski294@gmail.com', ]
            #send_mail( subject, message, email_from, recipient_list )
            emaail_local( subject, message, email_from, str(recipient_list) )

        return redirect('client:profile')

    else:
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()

    form = ShipForm()
    context = {'form':form,'items':items, 'order':order}
    return render(request, 'cart/checkout.html', context)


class CartDelete(DeleteView):
    model = OrderItem
    template_name = 'cart/delete.html'
    success_url = reverse_lazy('client:cart')


def cart(request):
    # request.user.is_authenticated
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = OrderItem.objects.filter(order=order)
    else:
        items = []

client/templates/profile.html
{% extends "home.html" %}

{% block content-m %}
    <div class="container-md">
        <h2 class="mb-3">Profilo utente</h2>
        <div class="row">
            <div class="col-md-6">
                <h4>Username</h4>
                <p>
                    {{ user.first_name}}
                </p>
            </div>
            <div class="col-md-6">
                <h4>Email</h4>
                <p>
                    {{ user.email }}
                </p>
            </div>
        </div>
    </div>

    <ul class="nav nav-pills"  role="tablist">
        <li class="nav-item"><a class="nav-link active" href="#booking" aria-controls="booking" role="tab" data-toggle="tab">Booking</a></li>
        <li class="nav-item"><a class="nav-link " href="#order" aria-controls="order" role="tab" data-toggle="tab">Order</a></li>
        <li class="nav-item"><a class="nav-link " href="#old_order" aria-controls="old_order" role="tab" data-toggle="tab">Old Order</a></li>
    </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active"  id="booking">
            <table class="table table-striped" id="table_id">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Date start</th>
                    <th>Date end</th>
                    <th>Chair</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for Booking in object_list %}
                    <tr>
                        <td>{{ Booking.name }}</td>
                        <td>{{ Booking.description }}</td>
                        <td>{{ Booking.date_start }}</td>
                        <td>{{ Booking.date_end }}</td>
                        <td>{{ Booking.chair }}</td>
                        <td>
                            <a class="btn btn-danger"
                               href="{% url 'client:booking-delete' Booking.id %}">
                                <i class='far fa-trash-alt'></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div role="tabpanel" class="tab-pane " id="order">
            <table class="table table-striped" id="table_id2">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Size</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for item in order_items_false %}
                    <tr>
                        <td><p>{{item.product.name}}</p></td>
                        <td><p>{{item.size}}</p></td>
                        <td><p>{{item.quantity}}</p></td>
                        <td><p>€{{item.product.price|floatformat:2}}</p></td>
                        <td>
                            <a class="btn btn-danger"
                               href="{% url 'client:cart-delete' item.id %}">
                                <i class='far fa-trash-alt'></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div role="tabpanel" class="tab-pane " id="old_order">
            <table class="table table-striped" id="table_id3">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Size</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                {% for item in order_items_true %}
                    <tr>
                        <td><p>{{item.product.name}}</p></td>
                        <td><p>{{item.size}}</p></td>
                        <td><p>{{item.quantity}}</p></td>
                        <td><p>€{{item.product.price|floatformat:2}}</p></td>
                        <td><p>{{item.order.date_ordered}}</p></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>



{% endblock %}

{% block javascript %}

    <script type="text/javascript">
        $(document).ready( function () {
            $('#table_id').DataTable();
            $('#table_id2').DataTable();
            $('#table_id3').DataTable();
        });
    </script>


{% endblock %}

client/templates/search.html
{% extends "main.html" %}

{% load crispy_forms_tags %}
{% block search %}
        <form class="form-inline my-2 my-lg-0" method="post">
            {% csrf_token %}
            {{ form | crispy   }}
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>


{% endblock %}