client/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings
from . import views

# python manage.py createsuperuser
app_name = 'client'

urlpatterns = [
	#Leave as empty string for base url
	path('', views.store, name="store"),
	path('<int:id>', views.store_eater, name="eater"),
	path('category/<int:id>', views.store_category, name="category"),
	path('view/<int:id>', views.detail_iteam, name="detail"),

	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),

	path('booking/', views.booking, name="booking"),
	path('booking/<int:pk>/delete', views.BookingDelete.as_view(), name="booking-delete"),
    path('cart/<int:pk>/delete', views.CartDelete.as_view(), name='cart-delete'),
	# ajax
	path('norm', views.normal_order, name="nornal"),
	path('camment', views.normal_comment, name="comment"),

    path('profile', views.profile_view, name='profile'),
    path('search', views.search, name='search'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



"""	
	path('checkout/', views.checkout, name="checkout"),

	path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),"""

pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#from pizza import views
from . import views


#app_name = 'pizza'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user_management.urls')),
    path('iteam/', include('client.urls')),
    path('', views.homepage, name='homepage'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models
#from django.contrib.auth.models import User
# Create your models here.
from django.utils import timezone
from pizza.settings import AUTH_USER_MODEL as User
## https://www.google.com/search?q=type+of+vegan+vegetarian+or+meat&tbm=isch&ved=2ahUKEwialZfn0qnrAhUSaBoKHSgvDocQ2-cCegQIABAA&oq=type+of+vegan+vegetarian+or+meat&gs_lcp=CgNpbWcQAzoECAAQQzoCCAA6BQgAELEDOgQIABATOgQIABAeULTMBVjsrgZg0K8GaABwAHgAgAHIAYgBuBeSAQY2LjIyLjSYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=RFo-X5rjNpLQaajeuLgI&bih=951&biw=1853&client=firefox-b-d#imgrc=snrGDYeF0EkiuM&imgdii=JynMuMmCgcai1M


class AddedThePizza(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()


class Product(models.Model):
    SIZE_CHOICES = [
        ('vegan', 'vegan'),
        ('vegetarian', 'vegetarian'),
        ('carnivore', 'carnivore'),
        ('Omnivore', 'Omnivore'),
    ]
    SIZE_CHOICES2 = [
        ('pizza', 'pizza'),
        ('sweet', 'sweet'),
        ('other', 'other'),
        ('drink', 'drink'),
    ]
    name = models.CharField(max_length=200)
    type_product = models.CharField(max_length=200,null=True,choices=SIZE_CHOICES2)
    type_eater = models.CharField(max_length=200,null=True,choices=SIZE_CHOICES) # https://themissinggraph.wordpress.com/2011/04/11/we-are-what-we-eat-an-infographic/
    price = models.FloatField()
    description = models.TextField(null=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    #product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date_ordered = models.DateTimeField(default=timezone.now, null=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total



class OrderItem(models.Model):
    SIZE_CHOICES = [
        ('normale', 'normale'),
        ('piccolo', 'piccolo'),
        ('grande', 'grande'),
        ('mezzo metro', 'mezzo metro'),
    ]
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    addpizza = models.ForeignKey(AddedThePizza, on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    size = models.CharField(max_length=50,choices=SIZE_CHOICES, default="normale")
    quantity = models.IntegerField(default=1, null=True, blank=True)
    # aggiunte (verdure carne e altro)
    date_added = models.DateTimeField(default=timezone.now, null=True, blank=True)

    @property
    def get_total(self):
        """if self.addpizza:
            add_pizza = self.addpizza.price
        else:
            add_pizza = 0"""

        total = (self.product.price * self.quantity) + (self.addpizza.price * self.quantity)
        return total


class Booking(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, null=True,blank=True)
    description = models.TextField(null=True, blank=True)
    chair = models.IntegerField(default=1, null=True, blank=True)
    date_start = models.DateTimeField(default=timezone.now, null=True, blank=True)
    date_end = models.DateTimeField(default=timezone.now, null=True, blank=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    comment = models.TextField(null=True, blank=True)
    rate = models.FloatField(default=1, null=True, blank=True)

    def __str__(self):
        return self.comment



class ShippingAddress(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=5, null=False)
    card_pay = models.CharField(max_length=10, null=False)
    date_added = models.DateTimeField(default=timezone.now, null=True, blank=True)

    def __str__(self):
        return self.address

client/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import datetime
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from .models import *
from .forms import *
#from .utils import cookieCart, cartData, guestOrder

from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages


def emaail_local(subject, message, email_from, recipient_list):
    print("##########################################################################")
    print("\n\n\nSubject : "+subject)
    print("Email_from : "+ email_from)
    print("Message : "+ message)
    print("Recipient_list : "+ recipient_list+"\n\n\n")
    print("##########################################################################")


def store(request):
    form2 = None
    products = None
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data.get('search'))
            products = Product.objects.filter(Q(name__contains=form.cleaned_data.get('search')) |
                                              Q(description__contains=form.cleaned_data.get('search')) |
                                              Q(type_eater__contains=form.cleaned_data.get('search')) ).order_by('name')

            context = {'products': products}
            return render(request, 'product/product.html', context)

    elif request.method == 'GET' and request.GET.get('tank', False) :
        print(request.GET.get('tank'))
        if request.GET.get('tank') == '1':
            products = Product.objects.all().order_by('name')
        elif request.GET.get('tank') == '2' :
            products = Product.objects.all().order_by('-name')
        elif request.GET.get('tank') == '3' :
            products = Product.objects.all().order_by('price')
        else:
            products = Product.objects.all().order_by('-price')


        form = SearchForm()
        form2 = ProductOrderForm()
    else:
        products = Product.objects.all().order_by('price')
        form = SearchForm()
        form2 = ProductOrderForm()

    context = {'form':form, 'form2':form2,'products': products }
    return render(request, 'product/product.html', context)


def store_eater(request,id):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data.get('search'))
            products = Product.objects.filter(Q(name__contains=form.cleaned_data.get('search')) |
                                              Q(description__contains=form.cleaned_data.get('search')) |
                                              Q(type_eater__contains=form.cleaned_data.get('search')) ).order_by('name')
            context = {'products': products}
            return render(request, 'product/product.html', context)
    else:
        if id == 1:
            products = Product.objects.filter(type_eater="vegan")
        elif id == 2:
            products = Product.objects.filter(type_eater="vegetarian")
        else:
            products = Product.objects.filter(type_eater="carnivore")
        form = SearchForm()

    context = {'form':form, 'products': products }
    return render(request, 'product/product.html', context)


def store_category(request,id):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data.get('search'))
            products = Product.objects.filter(Q(name__contains=form.cleaned_data.get('search')) |
                                              Q(description__contains=form.cleaned_data.get('search')) |
                                              Q(type_eater__contains=form.cleaned_data.get('search')) ).order_by('name')
            context = {'products': products}
            return render(request, 'product/product.html', context)
    else:
        if id == 1:
            products = Product.objects.filter(type_product="other")
        elif id == 2:
            products = Product.objects.filter(type_product="drink")
        else:
            products = Product.objects.filter(type_product="sweet")
        form = SearchForm()

    context = {'form':form, 'products': products }
    return render(request, 'product/product.html', context)


# http://127.0.0.1:8000/accounts/login?next=/iteam/view/2
def normal_order(request):
    #product = Product.objects.get(id=id)
    #print(request.POST.get('username'))
    data = { 'is_taken': False }
    if request.method == 'POST' and request.user.is_authenticated:
        data = { 'is_taken': True }
        customer = request.user
        product = Product.objects.get(id=request.POST.get('username'))
        order,created = Order.objects.get_or_create(customer=customer, complete=False)
        adpizza = AddedThePizza.objects.get(name="niente")
        orde = OrderItem.objects.create(product=product,order=order,size="normale",quantity=1,date_added=datetime.today().strftime('%Y-%m-%d'),addpizza=adpizza)
        orde.save()
        return JsonResponse(data)
    return JsonResponse(data)

#ajax
def normal_comment(request):
    data = { 'is_taken': False }
    if request.method == 'POST' and request.user.is_authenticated:
        data = { 'is_taken': True }

        product = Product.objects.get(id=request.POST.get('product'))
        com = Comment.objects.create(comment=request.POST.get('comment'), rate=request.POST.get('rate'),product=product, customer=request.user)
        com.save()
        return JsonResponse(data)
    return JsonResponse(data)


# AJAX non si puo mandare varile url template con int id in ajax likeeeeee {% url 'client:detail' product.id %}
# AJAX pero si possono fare degli escamotage(----with trick---) mettere url in un attributo e dopo con le funzioni javascipt o jquery
# AJAX O COME HO FATTO IO SOPRA
@login_required(login_url='/accounts/login')
def detail_iteam(request, id):
    rate = 0
    media_star = 0
    comment = []
    count = 0
    product = Product.objects.get(id=id)
    products2 = []
    ycomment=[]
    #print(product.type_eater)
    if request.method == 'POST':
        customer = request.user
        form = ProductDetailForm(request.POST)

        if form.is_valid():
            print(form.cleaned_data.get('side_dish'))
            order,created = Order.objects.get_or_create(customer=customer, complete=False)
            orderItem = form.save(commit=False)
            orderItem.product = product
            orderItem.order = order
            orderItem.addpizza = AddedThePizza.objects.get(id=form.cleaned_data.get('side_dish')) # devo aggiungere 0 default 0
            orderItem.date_added = datetime.today().strftime('%Y-%m-%d')
            orderItem.save()
            messages.success(request, 'Aggiunto al carrello!')
        else:
            messages.error(request, 'Salvataggio non ha avuto successo!')

        return redirect('client:store')
    else:
        form = ProductDetailForm()
        comment = Comment.objects.filter(product=product)
        ycomment = Comment.objects.filter(Q(product__type_eater=product.type_eater), ~Q(product=product))
        ycomment2 = ycomment.values_list('product', flat=True)
        try:
            products2 = Product.objects.filter(Q(type_eater=product.type_eater), ~Q(id=id), ~Q(id__in=ycomment2))
            #products2 = Product.objects.filter(Q(type_eater=product.type_eater), ~Q(id=id))
        except Order.DoesNotExist:
            products2 = []

        print(ycomment)
        print(products2)
        for x in comment:
            rate = x.rate + rate
        count = Comment.objects.filter(product=product).count()
        try:
            media_star =  (rate / count)
        except ZeroDivisionError:
            media_star = 0
        #form2 = CommentForm()

    context = {'product': product, 'products2': products2, 'ycomment': ycomment,'form':form, 'media_star':media_star, 'comment':comment, 'count':count}
    return render(request, 'product/product_view.html', context)


# ancora da sistemare
@login_required(login_url='/accounts/login')
def checkout(request):
    items = None
    order = None
    customer = request.user
    if request.method == 'POST':
        form = ShipForm(request.POST)
        if form.is_valid():
            form.save()
            complete_rder = Order.objects.get(customer=customer, complete=False)
            complete_rder.complete=True
            complete_rder.date_ordered=timezone.now()
            complete_rder.save()
            # eamil
            subject = 'Thank you for checkout to our site'
            message = "see you next time. date order : " + str(complete_rder.date_ordered)
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [complete_rder.customer.email]
            #recipient_list = ['jaski294@gmail.com', ]
            #send_mail( subject, message, email_from, recipient_list )
            emaail_local( subject, message, email_from, str(recipient_list) )

        return redirect('client:profile')

    else:
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()

    form = ShipForm()
    context = {'form':form,'items':items, 'order':order}
    return render(request, 'cart/checkout.html', context)


class CartDelete(DeleteView):
    model = OrderItem
    template_name = 'cart/delete.html'
    success_url = reverse_lazy('client:cart')


def cart(request):
    # request.user.is_authenticated
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = OrderItem.objects.filter(order=order)
    else:
        items = []

client/templates/product/product.html
{% extends "search.html" %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="alert alert-success fade in" id="bsalert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Info!</strong> This alert box could indicate a neutral informative or action
    </div>
    <form class="form-inline my-2 my-lg-0" method="get">
        {% csrf_token %}
        {{ form2 | crispy   }}
    </form>
    <div class="row">
        {% for product in products %}
            <div class="col-md-3" style=" padding: 20px">
                <div class="card" style="width: 24rem;">
                    <img src="{{product.image.url}}" class="img-thumbnail">
                    <div class="card-body">
                        <h5 class="card-title"><strong>{{product.name}}</strong></h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <button data-product="{{ product.id }}" type="button" data-action="add" class="btn btn-outline-secondary add-btn update-cart send_data">Add to Cart</button>
                        <a href="{% url 'client:detail' product.id %}" class="btn btn-success add-btn update-cart">view</a>
                        <h4 style="display: inline-block; float: right"><strong>€{{product.price}}</strong></h4>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

{% block javascript %}

    <script type="text/javascript">
        $(document).ready(function(){
            function toggleAlert(){
                $(".alert").toggleClass('in show');
                return false; // Keep close.bs.alert event from removing from DOM
            }
            $('#bsalert').on('close.bs.alert', toggleAlert);

            $(".send_data").click(function () {
                var ci = $(this).attr("data-product");
                //alert(ci);

                $.ajax({
                    type: 'POST',
                    url: '{% url "client:nornal" %}',
                    data: {
                        username: ci, csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.is_taken) {
                            //alert("A user with this username already exists.");
                            $(".alert").toggleClass('in show');
                            //return false;
                        }
                        else {
                            //alert("maleeeeeeeeeeee.");
                            window.location.assign("/accounts/login?next=" + window.location.pathname)

                        }
                    },
                    error : function (richiesta,stato,errori) {
                        alert("E' evvenuto un errore. Il stato della chiamata: "+stato);
                    }
                });

            });

        });

    </script>



{% endblock %}

client/templates/product/product_view.html
{% extends "home.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        {% if messages %}
            <ul class="messages" style="padding: 0px;">
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="row">
            <h1 class="card-title" ><strong>{{product.name}}</strong></h1>
            <h3>     Rate :{{ count }}</h3>
            <div id="id_rate2"></div>
        </div>
        <div class="row">
            <div class="col">
                <img src="{{product.image.url}}" class="card-img-top">
            </div>
            <div class="col">
                <p class="card-text">{{ product.description }}</p>
                <h4 style="display: inline-block; float: right"><strong>€{{product.price}}</strong></h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy  }}
                    <button type="submit"  class="button btn btn-success form-sub"  style="margin-top: 22px">add to cart</button>
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <h4>Write your review</h4>
        <div id="id_rate"></div>
        <input type="text" id="fname" name="fname">
        <button type="button" data-product="{{ product.id }}" class="button btn btn-success form-sub send_data"  style="margin-top: 22px">add to cart</button>
    </div>

    <div class="container">
        {% for iteam in comment %}
            <p><strong>{{iteam.customer.first_name}}</strong> : {{ iteam.comment }}</p>
        {% endfor %}
    </div>
    <br>
    <h3>Recommend for you</h3>
    <div class="row">
        {% for product2 in ycomment %}
            <div class="col-md-4" style=" padding: 20px">
                <div class="card" style="width: 24rem;">
                    <img src="{{product2.product.image.url}}" class="img-thumbnail">
                    <div class="card-body">
                        <h5 class="card-title"><strong>{{product2.product.name}}</strong></h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="{% url 'client:detail' product2.product.id %}" class="btn btn-success add-btn update-cart">view</a>
                        <h4 style="display: inline-block; float: right"><strong>€{{product2.product.price}}</strong></h4>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% for product2 in products2 %}
            <div class="col-md-4" style=" padding: 20px">
                <div class="card" style="width: 24rem;">
                    <img src="{{product2.image.url}}" class="img-thumbnail">
                    <div class="card-body">
                        <h5 class="card-title"><strong>{{product2.name}}</strong></h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="{% url 'client:detail' product2.id %}" class="btn btn-success add-btn update-cart">view</a>
                        <h4 style="display: inline-block; float: right"><strong>€{{product2.price}}</strong></h4>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#id_rate").rateYo({
                rating: 5
            });

            $("#id_rate2").rateYo({
                rating: {{ media_star }},
                readOnly: true

            });

            $(".send_data").click(function () {
                var normalFill = $("#id_rate").rateYo("option", "rating");
                var ci = $(this).attr("data-product");
                //alert(ci);
                var text_coment = $("#fname").val()
                $.ajax({
                    type: 'POST',
                    url: '{% url "client:comment" %}',
                    data: {
                        product: ci, comment: text_coment, rate: normalFill, csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.is_taken) {
                            alert("ottimo");
                        }
                        else {
                            alert("maleeeeeeeeeeee.");
                            //window.location.assign("/accounts/login?next=" + window.location.pathname)

                        }
                    },
                    error : function (richiesta,stato,errori) {
                        alert("E' evvenuto un errore. Il stato della chiamata: "+stato);
                    }
                });

            });

        });

    </script>



{% endblock %}