client/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings
from . import views

# python manage.py createsuperuser
app_name = 'client'

urlpatterns = [
	#Leave as empty string for base url
	path('', views.store, name="store"),
	path('<int:id>', views.store_eater, name="eater"),
	path('category/<int:id>', views.store_category, name="category"),
	path('view/<int:id>', views.detail_iteam, name="detail"),

	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),

	path('booking/', views.booking, name="booking"),
	path('booking/<int:pk>/delete', views.BookingDelete.as_view(), name="booking-delete"),
    path('cart/<int:pk>/delete', views.CartDelete.as_view(), name='cart-delete'),
	# ajax
	path('norm', views.normal_order, name="nornal"),
	path('camment', views.normal_comment, name="comment"),

    path('profile', views.profile_view, name='profile'),
    path('search', views.search, name='search'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



"""	
	path('checkout/', views.checkout, name="checkout"),

	path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),"""

pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#from pizza import views
from . import views


#app_name = 'pizza'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user_management.urls')),
    path('iteam/', include('client.urls')),
    path('', views.homepage, name='homepage'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user_management import views
from django.conf.urls.static import static
from django.conf import settings
#from django.contrib.auth.urls

app_name = 'user_management'

urlpatterns = [
    path('dashborad', views.dashborad, name='dashborad'),
    path('user/reg', views.UserCreateView.as_view(), name='user-register'),
    #django default view
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),

    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #product
    path('product/add', views.ProductAdd.as_view(), name='product-add'),
    path('product/<int:pk>/delete', views.ProductDelete.as_view(), name='product-delete'),
    path('product/<int:pk>/update', views.ProductUpdate.as_view(), name='product-update'),
    path('product/view', views.ProductView.as_view(), name='product-view'),
    #ingredienti
    path('ingredienti/add', views.IngredientiAdd.as_view(), name='ingredienti-add'),
    path('ingredienti/<int:pk>/delete', views.IngredientiDelete.as_view(), name='ingredienti-delete'),
    path('ingredienti/<int:pk>/update', views.IngredientiUpdate.as_view(), name='ingredienti-update'),
    path('ingredienti/view', views.IngredientiView.as_view(), name='ingredienti-view'),
    #addpizza
    path('addpizza/add', views.AddedThePizzaAdd.as_view(), name='addpizza-add'),
    path('addpizza/<int:pk>/delete', views.AddedThePizzaDelete.as_view(), name='addpizza-delete'),
    path('addpizza/<int:pk>/update', views.AddedThePizzaUpdate.as_view(), name='addpizza-update'),
    path('addpizza/view', views.AddedThePizzaView.as_view(), name='addpizza-view'),
    #person
    path('person/add', views.PersonAdd.as_view(), name='person-add'),
    path('person/<int:pk>/delete', views.PersonDelete.as_view(), name='person-delete'),
    path('person/<int:pk>/update', views.PersonUpdate.as_view(), name='person-update'),
    path('person/view', views.PersonView.as_view(), name='person-view'),

    path('booking/view', views.BookingView.as_view(), name='booking-view'),
    path('grafico', views.grafico, name='grafico-view'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static '/css/login.css' %}" >
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="logged-out not-pro not-player not-self not-team not-on-team  sign-in">
<div id="main-container">
    <section class="auth-sidebar">
        <div class="auth-sidebar-content">
            <header>
                <h1><a href="/" class="logo">PIZZA</a></h1>
                <h1>Discover the world’s Pizza.</h1>
            </header>
            <div class="artwork">
                <div class="artwork-image"></div>
            </div>
        </div>
    </section>
    <section class="content">
        <main>
            <div class="auth-content">
                <h1>Sign in to Pizza</h1>

                <div class="auth-form sign-in-form">

                    {% block content %}


                    {% endblock content %}
                </div>
            </div>
        </main>
    </section>
</div>
</body>
</html>

templates/dashboard.html
{% extends "home.html" %}

{% block menu2 %}
    <style>
        body {
            font-family: "Lato", sans-serif;
            transition: background-color .5s;
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

        .sidenav a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .sidenav .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        #main {
            transition: margin-left .5s;
            padding: 0px;
        }

        @media screen and (max-height: 450px) {
            .sidenav {padding-top: 15px;}
            .sidenav a {font-size: 18px;}
        }
    </style>
    </head>
    <body>

    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'user_management:product-view' %}">Product</a>
        <a href="{% url 'user_management:addpizza-view' %}">AddPizza</a>
        <a href="{% url 'user_management:booking-view' %}">Booking</a>
        <a href="{% url 'user_management:grafico-view' %}">Grafico</a>
        <a href="{% url 'user_management:ingredienti-view' %}">Ingredienti</a>
    </div>

    <div id="main">
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </div>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
            document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft= "0";
            document.body.style.backgroundColor = "white";
        }
    </script>
{% endblock menu2 %}

templates/dashboardmenu.html
{% extends "main.html" %}

{% block menu2 %}
    <style>
        body {
            font-family: "Lato", sans-serif;
            transition: background-color .5s;
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

        .sidenav a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .sidenav .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        #main {
            transition: margin-left .5s;
            padding: 0px;
        }

        @media screen and (max-height: 450px) {
            .sidenav {padding-top: 15px;}
            .sidenav a {font-size: 18px;}
        }
    </style>
    </head>
    <body>

    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'user_management:product-view' %}">Product</a>
        <a href="{% url 'user_management:addpizza-view' %}">AddPizza</a>
        <a href="{% url 'user_management:booking-view' %}">Booking</a>
        <a href="{% url 'user_management:grafico-view' %}">Grafico</a>
        <a href="{% url 'user_management:ingredienti-view' %}">Ingredienti</a>
    </div>

    <div id="main">
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
    </div>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
            document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft= "0";
            document.body.style.backgroundColor = "white";
        }
    </script>
{% endblock menu2 %}

templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <title>Pizza Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/prova.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap-material-datetimepicker.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />

    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.10/css/bootstrap-material-design.min.css"/>-->
    <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.10/css/ripples.min.css"/>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<!--<h1 id="ciao">ddddddddddddddddddddddddddddd</h1>-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% block menu2 %}{% endblock menu2 %}
    <a class="navbar-brand" href="/">Pizza house</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'client:store' %}">Product</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pizza
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "client:eater" 1 %}">Vegan</a>
                    <a class="dropdown-item" href="{% url "client:eater" 2 %}">Vegetarian</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url "client:eater" 3 %}">Carnivore</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'client:booking' %}">Booking</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "client:category" 1 %}">Other product</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "client:category" 2 %}">Drinks</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "client:category" 3 %}">Sweets</a>
            </li>
        </ul>
        {% block search %}{% endblock search %}
        <div class="dropdown">
            <button class="btn dropdown-toggle btn-outline-success" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.first_name }} <i class="fas fa-user"></i></button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'client:profile' %}">Profile</a>
                {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'user_management:logout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'user_management:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
        <a class="btn btn-outline-success " type="submit" href="{% url 'client:cart' %}"><span class="badge badge-light">{{order.get_cart_items}}</span><i class="fas fa-shopping-cart"></i></a>
    </div>
</nav>
<div class="container-fluid">
    {% block content %}{% endblock content %}
</div>
<div class="container-xl">
    {% block content-m %}{% endblock content-m %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/57632e5759.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.10/js/ripples.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.10/js/material.min.js"></script>
<script type="text/javascript" src="http://momentjs.com/downloads/moment-with-locales.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-material-datetimepicker.js' %}"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>


{% block javascript %}{% endblock %}
</body>
</html>

templates/main.html
{% extends "home.html" %}

{% block content %}

    <div class="row justify-content-md-center">
        <div class="col"></div>
        <div class="col-10">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="images/slide/pizza_1.jpg" class="d-block " alt="..."  width="1500" height="770" >
                    </div>
                    <div class="carousel-item">
                        <img src="images/slide/pizza_2.jpg" class="d-block " alt="..."  width="1500" height="770">
                    </div>
                    <div class="carousel-item">
                        <img src="images/slide/pizza_3.jpg" class="d-block " alt="..." width="1500" height="770">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col"> </div>
    </div>

    <br>
    <br>

    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="images/slide/pizza_1.jpg" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" role="img" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/></img>

                <h2>Vegan</h2>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                <p><a class="btn btn-success" href="{% url "client:eater" 1 %}" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->

            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="images/slide/pizza_2.jpg" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" role="img" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/></img>

                <h2>Vegetarian</h2>
                <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                <p><a class="btn btn-success" href="{% url "client:eater" 2 %}" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="images/slide/pizza_3.jpg" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" role="img" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/></img>

                <h2>Carnivore</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-success" href="{% url "client:eater" 3 %}" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading"><span class="text-muted">Other product</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                <p><a class="btn btn-success" href="{% url "client:category" 1 %}" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-5">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="images/slide/other_1.jpg" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" role="img" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/></img>

            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7 order-md-2">
                <h2 class="featurette-heading"><span class="text-muted">Drinks</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                <p><a class="btn btn-success" href="{% url "client:category" 2 %}" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-5 order-md-1">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="images/slide/drink_1.jpeg"  aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" role="img" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/></img>

            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading"><span class="text-muted">Sweets</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                <p><a class="btn btn-success" href="{% url "client:category" 3 %}" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-5">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="images/slide/doce_1.jpg" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" role="img" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/></img>

            </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->


{% endblock content %}